services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - observability-network

  dc-ubuntu:
    build:
      context: ./dc-ubuntu
    container_name: dc-ubuntu
    ports:
      - "2222:22"
      - "9100:9100"
    networks:
      - observability-network
    volumes:
      - dc-ubuntu-bin:/usr/local/bin

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    networks:
      - observability-network
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  dc-ubuntu-bin:
  grafana-storage:

networks:
  observability-network:
    driver: bridge
